name: Maven CI/CD
on:
 push:
 workflow_dispatch:
  inputs:
    evs_version:
      description: "Overwrite EVS version (default to the one in release/version_input.txt)"
      required: false
    create_artifacts:
      description: "Produce temporary artifacts"
      required: false
    create_release:
      description: "Produce the release artifacts"
      required: false
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: â˜• Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: ğŸš€ Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: âœ¨ Fix permissions
        run: |
          chmod u+x builder/release.sh 
      - name: ğŸ‘€ Detect wanted version
        shell: bash
        run: |
          if [[ -z "${{ github.event.inputs.evs_version }}" ]]; then 
            export EVS_VERSION=$(head -n 1 release/version_input.txt) 
          else 
            export EVS_VERSION=${{ github.event.inputs.evs_version }} 
          fi 
          echo "EVS_VERSION=${EVS_VERSION}" >> $GITHUB_ENV
      - name: ğŸ“¨ Set wanted version
        run: |
          echo "${{ env.EVS_VERSION }}" > release/version_input.txt
      - name: ğŸ”¨ Build project with Maven
        run: |
          cd builder && ./release.sh
      - name: ğŸš§ Workaround actions/upload-artifact#176
        run: |
          echo "artifacts_path=$(realpath ../builds/${{ env.EVS_VERSION }})" >> $GITHUB_ENV
      - name: ğŸ§° Create release zip
        if: github.event.inputs.create_artifacts || github.event.inputs.create_release
        run: zip -r -q EVS-${{ env.EVS_VERSION }}).zip ${{ env.artifacts_path }}
      - name: ğŸ“ Archive artifacts
        uses: actions/upload-artifact@v3
        if: github.event.inputs.create_artifacts
        with:
          name: EVS-build
          path: ${{ env.artifacts_path }}
      - uses: ncipollo/release-action@v1.13.0
        name: ğŸ¤– Create release on Github
        if: github.event.inputs.create_release
        with:
          artifacts: "EVS-${{ env.EVS_VERSION }}).zip"
          allowUpdates: "true"
          tag: "${{ env.EVS_VERSION }})"
          commit: "main"
          name: "EVS-${{ env.EVS_VERSION }})"