name: Maven CI/CD
on:
 push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: â˜• Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: ğŸš€ Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: âœ¨ Fix permissions
        run: |
          chmod u+x builder/release.sh 
      - name: ğŸ”¨ Build project with Maven
        run: |
          cd builder && ./release.sh
      - name: ğŸ“ Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: EVS-build
          path: |
            ../../builds